import Head from "next/head";
import Hero from "../components/HomeComponents/Hero";
import Projects from "../components/HomeComponents/Projects";
import Navbar from "../components/ui/Navbar";
import Services from "../components/HomeComponents/Services";
import CTA from "../components/HomeComponents/CTA";
import AboutUs from "../components/HomeComponents/AboutsUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Projects />
      <AboutUs />
      <Services />
      <CTA />
    </>
  );
}
